#include <clang/Basic/Version.h>

#define TEST_SOURCE_DIR "@CMAKE_CURRENT_SOURCE_DIR@"

#define QT5_REQUIRED_COMPILER_FLAGS @QT5_REQUIRED_COMPILER_FLAGS@

#define CLANG_BUILTIN_INCLUDES_PATH "@CLANG_LIBRARY_DIR@" "/clang/" CLANG_VERSION_STRING "/include"
